[package]
name = "postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = "2.0.0"
serde = "1.0.148"
cyndra-poem = "0.38.0"
cyndra-runtime = "0.38.0"
cyndra-shared-db = { version = "0.38.0", features = ["postgres", "sqlx"] }
sqlx = "0.7.1"
tokio = "1.26.0"
