[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
salvo = "0.41.0"
cyndra-salvo = { version = "0.17.0" }
cyndra-runtime = { version = "0.17.0" }
tokio = { version = "1.26.0" }

