[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
cyndra-poise = { version = "0.15.0" }
cyndra-runtime = { version = "0.15.0" }
cyndra-secrets = "0.15.0"
tracing = "0.1.37"
tokio = { version = "1.26.0" }
