[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
cyndra-service = { version = "0.11.0", features = ["bot-poise"] }
anyhow = "1.0.68"
cyndra-secrets = "0.11.0"
tracing = "0.1.37"
poise = "0.5.2"
