[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.5.2"
cyndra-poise = "0.36.0"
cyndra-runtime = "0.36.0"
cyndra-secrets = "0.36.0"
tracing = "0.1.37"
tokio = "1.26.0"
