[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
cyndra-thruster = { version = "0.16.0" }
cyndra-runtime = { version = "0.16.0" }
thruster = { version = "1.3.0", features = ["hyper_server"] }
tokio = { version = "1.26.0" }
