[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
axum = { version = "0.6.0", features = ["ws"] }
chrono = { version = "0.4.23", features = ["serde"] }
futures = "0.3.25"
hyper = { version = "0.14.23", features = ["client", "http2"] }
hyper-tls = "0.5.0"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
cyndra-service = { version = "0.7.2", features = ["web-axum"] }
sync_wrapper = "0.1.1"
tokio = { version = "1.22.0", features = ["full"] }
