[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
cyndra-tide = { version = "0.13.0" }
cyndra-runtime = { version = "0.13.0" }
tokio = { version = "1.26.0" }
tide = "0.16.0"
