[package]
name = "persist"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
cyndra-persist = "0.6.0"
cyndra-service = { version = "0.6.0", features = ["web-rocket"] }
