[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
cyndra-runtime = { version = "0.16.0" }
cyndra-warp = { version = "0.16.0" }
tokio = { version = "1.26.0" }
warp = "0.3.3"
