[package]
name = "turso-example"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
cyndra-axum = "0.37.0"
cyndra-runtime = "0.37.0"
cyndra-turso = "0.37.0"
libsql = "0.2.0"
tokio = "1.26.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
