[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
actix-service = "2.0.2"
cyndra-service = { version = '0.7.2', path = '../../../service', features = ["web-actix-web"] }

