[package]
name = "multi-binary"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "standalone"
path = "src/standalone.rs"

[dependencies]
axum = "0.6.18"
dotenvy = "0.15.7"
cyndra-axum = "0.27.0"
cyndra-runtime = "0.27.0"
cyndra-secrets = "0.27.0"
tokio = "1.28.2"
