[package]
name = "cyndra-axum-qdrant"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
qdrant-client = "1.10.1"
cyndra-axum = { version = "0.54.0", default-features = false, features = ["axum-0-7"] }
cyndra-qdrant = "0.54.0"
cyndra-runtime = "0.54.0"
tokio = "1.26.0"
